version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cms-app
    container_name: CMS-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel-net

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_CMS
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  db-data:

networks:
  laravel-net:
